#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Svg.Droid.SampleEditor.Resource", IsApplication=true)]

namespace Svg.Droid.SampleEditor
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Svg.Droid.SampleEditor.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Svg.Droid.SampleEditor.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Svg.Droid.SampleEditor.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Svg.Droid.SampleEditor.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Svg.Droid.SampleEditor.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Svg.Droid.SampleEditor.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Svg.Droid.SampleEditor.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Svg.Droid.SampleEditor.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Svg.Droid.SampleEditor.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Svg.Droid.SampleEditor.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_add_circle_outline_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_aspect_ratio_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_border_style_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_brush_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_code_white_48dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_color_lens_white_48dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_delete_white_48dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_grid_off_white_48dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_grid_on_white_48dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_line_style_white_48dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_mode_edit_white_48dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_pan_tool_white_48dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_redo_white_48dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_save_white_48dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_search_black_48dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_select_tool_white_48dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_text_fields_white_48dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_undo_white_48dp = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_zoom_100_white_48dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_zoom_200_white_48dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_zoom_in_white_48dp = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_zoom_out_white_48dp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_zoom_white_48dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int splash = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int MyButton = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int pad = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditorView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SplashScreen = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
